# Generated by Django 2.1.2 on 2018-10-31 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrorescatados',
            name='Fotografia',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
